export const GET_EXPENSE_LIST = '@DYNAMIC/GET_EXPENSE_LIST';
export const SAVE_EXPENSE_LIST = '@DYNAMIC/SAVE_EXPENSE_LIST';
export const GET_EXPENSE_META_DATA = '@DYNAMIC/GET_EXPENSE_META_DATA';
export const SAVE_EXPENSE_META_DATA = '@DYNAMIC/SAVE_EXPENSE_META_DATA';
export const SAVE_EXPENSE_SUMMARY = '@DYNAMIC/SAVE_EXPENSE_SUMMARY';
export const GET_EXPENSE_SUMMARY = '@DYNAMIC/GET_EXPENSE_SUMMARY';
export const SET_EXPENSE_STATUS = '@DYNAMIC/SET_EXPENSE_STATUS';

export const LINEAR_GRADIENT_START_VAL = {x: 0, y: 0};
export const LINEAR_GRADIENT_END_VAL = {x: 1, y: 1};
export const WHITE = '#fff';
