export const FETCH_OPPORTUNITY_METADATA = '@DYNAMIC/FETCH_OPPORTUNITY_METADATA';
export const FETCH_OPPS_STAGE_PROBABILITY =
  '@DYNAMIC/FETCH_OPPS_STAGE_PROBABILITY';
export const SAVE_OPPS_STAGE_PROBABILITY =
  '@DYNAMIC/SAVE_OPPS_STAGE_PROBABILITY';

export const SET_NEW_OPPORTUNITY = '@DYNAMIC/SET_NEW_OPPORTUNITY';
export const SET_OPPORTUNITY_VISIBILITY = '@DYNAMIC/SET_OPPORTUNITY_VISIBILITY';
export const SET_QUICK_VIEW_MODAL_STATE = '@DYNAMIC/SET_QUICK_VIEW_MODAL_STATE';
export const FETCH_OPPS_STAGES = '@DYNAMIC/FETCH_OPPS_STAGES';
export const SAVE_OPPS_STAGES = '@DYNAMIC/SAVE_OPPS_STAGES';

export const FETCH_USER_DD_LIST = '@DYNAMIC/FETCH_USER_DD_LIST';
export const FETCH_ORG_DD_LIST = '@DYNAMIC/FETCH_ORG_DD_LIST';

export const SAVE_USER_DD_LIST = '@DYNAMIC/SAVE_USER_DD_LIST';
export const SAVE_ORG_DD_LIST = '@DYNAMIC/SAVE_ORG_DD_LIST';

export const SAVE_OPPS_METADATA = '@DYNAMIC/SAVE_OPP_METADATA';
export const GET_IND_DD_VALUE = '@DYNAMIC/GET_IND_DD_VALUE';

export const OPP_FORM = '@DYNAMIC/OPP_FORM';
export const CREATE_OPP = '@DYNAMIC/CREATE_OPP';
