export const FETCH_OPPORTUNITY_METADATA = '@DYNAMIC/FETCH_OPPORTUNITY_METADATA';
export const FETCH_OPPS_STAGE_PROBABILITY =
  '@DYNAMIC/FETCH_OPPS_STAGE_PROBABILITY';
export const SAVE_OPPS_STAGE_PROBABILITY =
  '@DYNAMIC/SAVE_OPPS_STAGE_PROBABILITY';

export const FETCH_OPPS_STAGES = '@DYNAMIC/FETCH_OPPS_STAGE_PROBABILITY';
export const SAVE_OPPS_STAGES = '@DYNAMIC/SAVE_OPPS_STAGE_PROBABILITY';

export const FETCH_USER_DD_LIST = '@DYNAMIC/FETCH_USER_DD_LIST';
export const FETCH_ORG_DD_LIST = '@DYNAMIC/FETCH_ORG_DD_LIST';

export const SAVE_USER_DD_LIST = '@DYNAMIC/SAVE_USER_DD_LIST';
export const SAVE_ORG_DD_LIST = '@DYNAMIC/SAVE_ORG_DD_LIST';

export const SAVE_OPPS_METADATA = '@DYNAMIC/SAVE_OPP_METADATA';
