export const GET_EXPENSE_DETAILS = '@DYNAMIC/GET_EXPENSE_DETAILS';
export const SAVE_EXPENSE_DETAILS = '@DYNAMIC/SAVE_EXPENSE_DETAILS';
export const SET_CURRENT_EXPENSE_ID = '@DYNAMIC/SET_CURRENT_EXPENSE_ID';
